name: CI Workflow 4

on:
  schedule:
    - cron: '30 20 * * *'  # Ejecutar a las 2:15 CET

jobs:
  run_system_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        browser: [chrome, firefox, edge, safari]
        exclude:
          - os: ubuntu
            browser: edge

          - os: ubuntu
            browser: safari

          - os: windows
            browser: safari

          - os: macos
            browser: edge
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
