name: CI Workflow 3

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  test:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          node-version: '20'  # Aquí establece la versión de Node.js a 20

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        env:
          NODE_VERSION: '20'  # Establece la versión de Node.js en el entorno

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t poweer02/nitflex:${{ github.sha }} .
          docker push poweer02/nitflex:${{ github.sha }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: PoweeR02
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        env:
          NODE_VERSION: '20'  # Establece la versión de Node.js en el entorno

      - name: Smoke Test
        run: |
          mvn -Dhost=https://PoweeR02.azurewebsites.net test
