name: CI Workflow 4

on:
  schedule:
    - cron: '40 17 * * *'  # Ejecutar a las 2:15 CET

jobs:
  run_system_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            browser: chrome
          - os: ubuntu-latest
            browser: firefox
          - os: windows-latest
            browser: chrome
          - os: windows-latest
            browser: firefox
          - os: windows-latest
            browser: edge
          - os: macos-latest
            browser: chrome
          - os: macos-latest
            browser: firefox
          - os: macos-latest
            browser: safari

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
