name: Workflow 4

on:
  schedule:
    - cron: "54 11 * * *" # 10 : 36 -> "30 20 * * *"

jobs:
  system-tests:
    runs-on: matrix
    strategy:
      matrix:
        browser: [ chrome, firefox, edge, safari ]
        os: [ linux, windows, macos ]
        exclude:
          - browser: edge
            os: macos
          - browser: safari
            os: windows
          - browser: safari
            os: linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Run system tests
        run: |
          npm run test:system -- --browser ${{ matrix.browser }} --os ${{ matrix.os }}
