name: CI Workflow 4

on:
  push:
  schedule:
    - cron: "20 12 * * *" # 10 : 36 -> "30 20 * * *"

jobs:
  system-tests:
    runs-on: matrix
    strategy:
      matrix:
        browser: [ chrome, firefox, edge, safari ]
        os: [ linux, windows, macos ]
        exclude:
          - browser: edge
            os: macos
          - browser: safari
            os: windows
          - browser: safari
            os: linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run system tests
        run: |
          java -cp src/e2e/selenium SeleniumTest.java SeleniumBugTest.java FilmUITest.java \
            -Dbrowser=${{ matrix.browser }} \
            -Dos=${{ matrix.os }}
