name: CI Workflow 2

on:
  push:
    branches:
      - pruebas-2
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Run Unitary Testing
        run: mvn test -P unitary

      - name: Run Integration Testing
        run: mvn test -P integration

      - name: Run Selenium Test
        run: mvn test -P selenium 
      
