name: CI Workflow 4

on:
  schedule:
    - cron: '40 17 * * *'  # Ejecutar a las 2:15 CET

jobs:
  run_system_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chrome, firefox, edge, safari]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run system test
        run: npm test ${{ matrix.browser }} ${{ runner.os }}
