name: New Feature Request Workflow 2

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:        
      - name: Checkout code         
        uses: actions/checkout@v4
            
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Maven Unitary Tests
        run: mvn test -P unitary-tests
        

      - name: Run Maven Integration Tests
        run: mvn test -P integration
        

      - name: Run Maven Smoke Tests
        run: mvn test -P selenium